attnhr/attendance/urls.py
from django.urls import path

from . import views

app_name = 'attendance'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:employee_id>/', views.details, name='details')
]

attnhr/attnhr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('attendance/', include('attendance.urls')),
    path('admin/', admin.site.urls),
]

attnhr/attendance/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
	# empNo = models.IntegerField(primary_key=True)
	first_name = models.CharField(max_length=20)
	last_name = models.CharField(max_length=20)
	gender = models.CharField(max_length=1)
	hire_date = models.DateField()

	def __str__(self):
		return "{} {}".format(self.first_name, self.last_name)

class InOut(models.Model):
	CHECK_TYPE = (
        ('I', 'In'),
        ('O', 'Out'),
    )
	user_id = models.ForeignKey(Employee, on_delete=models.CASCADE)
	check_date = models.DateField()
	check_time = models.TimeField()
	check_type = models.CharField(max_length=1, choices=CHECK_TYPE)

	def __str__(self):
		return "{} : {} - {}".format(self.user_id, self.check_date, self.check_type)

attnhr/attendance/views.py
from django.shortcuts import get_object_or_404, render

from .models import Employee, InOut

# Create your views here.

def index(request):
	employee_list = Employee.objects.order_by('-hire_date')[:5]
	context = {'employee_list': employee_list}
	return render(request, 'attendance/index.html', context)

def details(request, employee_id):
	employees = get_object_or_404(Employee, id=employee_id)
	inouts = InOut.objects.filter(user_id = employee_id)

	context = {'employees' : employees,
	'inouts' : inouts
	}
	return render(request, 'attendance/details.html', context)

attnhr/attendance/templates/attendance/details.html
<h1>{{ employees.first_name }} {{ employees.last_name }}</h1>
<ul>

    <li>{% if employees.gender  == 'M' %}
    Male {% else%}
    Female	
    	{% endif %}
</li>
    <li>{{ employees.hire_date }}</li>

</ul>


{% if inouts %}
    <ul>
    {% for inout in inouts %}
        <li>{{ inout.check_date }} - {{ inout.check_time }}</a><strong>( {{ inout.check_type }} )</strong></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No records are available.</p>
{% endif %}

attnhr/attendance/templates/attendance/index.html
{% if employee_list %}
    <ul>
    {% for employee in employee_list %}
        <li><a href="{% url 'attendance:details' employee.id %}">{{ employee.first_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No employees are available.</p>
{% endif %}